resources:
  - "@type": "type.googleapis.com/envoy.api.v2.auth.Secret"
    tls_certificate:
      certificate_chain:
        filename: /etc/envoy/envoy.pem
      private_key:
        filename: /etc/envoy/envoy-key.pem
